config/routes.rb
Rails.application.routes.draw do

  resources :fmr_datasets, except: [:edit, :update]

  resources :fair_mkt_rents, only: [:index, :show]

  get '/ulw', to: 'ulw#show', as: :ulw
  get '/', to: 'ulw#search'
end

app/models/fair_mkt_rent.rb
class FairMktRent < ActiveRecord::Base
  belongs_to :fmr_dataset

  validates :fmr_dataset, presence: true
  validates :fmr0, :fmr1, :fmr2, :fmr3, :fmr4,
    :metro_code, :year, presence: true
  validates :metro_code,
    uniqueness: { scope: [:year, :fmr_dataset] }

  def self.by_metro_code(mcode, year = Time.now.year)
    find_by({year: year}.merge(mcode))
  end
end

app/controllers/fair_mkt_rents_controller.rb
# TODO: change this to pull from HUD API
class FairMktRentsController < ApplicationController
  before_action :set_fair_mkt_rent, only: [:show, :edit, :update, :destroy]

  # GET /fair_mkt_rents
  # GET /fair_mkt_rents.json
  def index
    @fair_mkt_rents = FairMktRent.all
  end

  # GET /fair_mkt_rents/1
  # GET /fair_mkt_rents/1.json
  def show
  end

  # GET /fair_mkt_rents/new
  def new
    @fair_mkt_rent = FairMktRent.new
  end

  # GET /fair_mkt_rents/1/edit
  def edit
  end

  # POST /fair_mkt_rents
  # POST /fair_mkt_rents.json
  def create
    @fair_mkt_rent = FairMktRent.new(fair_mkt_rent_params)

    respond_to do |format|
      if @fair_mkt_rent.save
        format.html { redirect_to @fair_mkt_rent, notice: 'Fair mkt rent was successfully created.' }
        format.json { render :show, status: :created, location: @fair_mkt_rent }
      else
        format.html { render :new }
        format.json { render json: @fair_mkt_rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fair_mkt_rents/1
  # PATCH/PUT /fair_mkt_rents/1.json
  def update
    respond_to do |format|
      if @fair_mkt_rent.update(fair_mkt_rent_params)
        format.html { redirect_to @fair_mkt_rent, notice: 'Fair mkt rent was successfully updated.' }
        format.json { render :show, status: :ok, location: @fair_mkt_rent }
      else
        format.html { render :edit }
        format.json { render json: @fair_mkt_rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fair_mkt_rents/1
  # DELETE /fair_mkt_rents/1.json
  def destroy
    @fair_mkt_rent.destroy
    respond_to do |format|
      format.html { redirect_to fair_mkt_rents_url, notice: 'Fair mkt rent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fair_mkt_rent
      @fair_mkt_rent = FairMktRent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fair_mkt_rent_params
      params.require(:fair_mkt_rent).permit(:fmr0, :fmr1, :fmr2, :fmr3, :fmr4, :metro_code, :year, :fmr_dataset_id)
    end
end

app/helpers/fair_mkt_rents_helper.rb
module FairMktRentsHelper
end

app/views/fair_mkt_rents/_form.html.slim
= simple_form_for(@fair_mkt_rent) do |f|
  = f.error_notification

  .form-inputs
    = f.input :fmr0
    = f.input :fmr1
    = f.input :fmr2
    = f.input :fmr3
    = f.input :fmr4
    = f.input :metro_code
    = f.input :year
    = f.association :fmr_dataset

  .form-actions
    = f.button :submit

app/views/fair_mkt_rents/edit.html.slim
h1 Editing fair_mkt_rent

== render 'form'

= link_to 'Show', @fair_mkt_rent
'|
= link_to 'Back', fair_mkt_rents_path

app/views/fair_mkt_rents/index.html.slim
h1 Listing fair_mkt_rents

table
  thead
    tr
      th Fmr0
      th Fmr1
      th Fmr2
      th Fmr3
      th Fmr4
      th Metro code
      th Year
      th Fmr dataset
      th
      th
      th

  tbody
    - @fair_mkt_rents.each do |fair_mkt_rent|
      tr
        td = fair_mkt_rent.fmr0
        td = fair_mkt_rent.fmr1
        td = fair_mkt_rent.fmr2
        td = fair_mkt_rent.fmr3
        td = fair_mkt_rent.fmr4
        td = fair_mkt_rent.metro_code
        td = fair_mkt_rent.year
        td = fair_mkt_rent.fmr_dataset
        td = link_to 'Show', fair_mkt_rent
        td = link_to 'Destroy', fair_mkt_rent, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Fair mkt rent', new_fair_mkt_rent_path

app/views/fair_mkt_rents/new.html.slim
h1 New fair_mkt_rent

== render 'form'

= link_to 'Back', fair_mkt_rents_path

app/views/fair_mkt_rents/show.html.slim
p#notice = notice

p
  strong Fmr0:
  = @fair_mkt_rent.fmr0
p
  strong Fmr1:
  = @fair_mkt_rent.fmr1
p
  strong Fmr2:
  = @fair_mkt_rent.fmr2
p
  strong Fmr3:
  = @fair_mkt_rent.fmr3
p
  strong Fmr4:
  = @fair_mkt_rent.fmr4
p
  strong Metro code:
  = @fair_mkt_rent.metro_code
p
  strong Year:
  = @fair_mkt_rent.year
p
  strong Fmr dataset:
  = @fair_mkt_rent.fmr_dataset

= link_to 'Back', fair_mkt_rents_path