config/routes.rb
Rails.application.routes.draw do

  resources :fmr_datasets, except: [:edit, :update]

  resources :fair_mkt_rents, only: [:index, :show]

  get '/ulw', to: 'ulw#show', as: :ulw
  get '/', to: 'ulw#search'
end

app/models/fmr_dataset.rb
class FmrDataset < ActiveRecord::Base
  has_many :fmr_areas, dependent: :destroy
  has_many :fair_mkt_rents, dependent: :destroy
  has_one  :dataset_var, dependent: :destroy
  accepts_nested_attributes_for :dataset_var

  validates :requested_by, :data_year, :method, :description, presence: true

  validates :data_year, uniqueness:
    { message: 'Only one dataset per year. Destroy previous dataset first' }
end

app/controllers/fmr_datasets_controller.rb
class FmrDatasetsController < ApplicationController
  before_action :set_fmr_dataset, only: [:show, :edit, :update, :destroy]

  # GET /fmr_datasets
  # GET /fmr_datasets.json
  def index
    @fmr_datasets = FmrDataset.all
  end

  # GET /fmr_datasets/1
  # GET /fmr_datasets/1.json
  def show
  end

  # GET /fmr_datasets/new
  def new
    @fmr_dataset = FmrDataset.new
    @fmr_dataset.dataset_var = DatasetVar.last || DatasetVar.new
  end

  # POST /fmr_datasets
  # POST /fmr_datasets.json
  def create
    @fmr_dataset = FmrDataset.new(fmr_dataset_params)
    @fmr_dataset.method = 'web upload'
    @fmr_dataset.dataset_var = DatasetVar.new(dataset_var_params)

    directory = 'lib/assets/fmr_dataset_spreadsheets'
    name = filename_params['filename']
    if name.present?
      path = Rails.root + directory + name.original_filename
      tempfile = File.open(name.tempfile)
      new_file = File.new(path, 'wb')

      IO.copy_stream(tempfile, new_file)
      tempfile.close
      new_file.close

      service = SaveSpreadsheetToDbService.new(path, @fmr_dataset, @fmr_dataset.dataset_var)
      service.perform
    end

    @fmr_dataset.dataset_var.filename = path

    begin
      @fmr_dataset.transaction do
        service.persist if service
        @fmr_dataset.dataset_var.save!
        @fmr_dataset.save!
      end
    rescue
      not_persisted = true
    end

    respond_to do |format|
      unless not_persisted
        format.html { redirect_to @fmr_dataset, notice: 'Fmr dataset was successfully created.' }
        format.json { render :show, status: :created, location: @fmr_dataset }
      else
        format.html { render :new }
        format.json { render json: @fmr_dataset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fmr_datasets/1
  # DELETE /fmr_datasets/1.json
  def destroy
    @fmr_dataset.destroy
    respond_to do |format|
      format.html { redirect_to fmr_datasets_url, notice: 'Fmr dataset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_fmr_dataset
    @fmr_dataset = FmrDataset.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def fmr_dataset_params
    params.require(:fmr_dataset).permit(:requested_by, :data_year, :method, :description)
  end

  def dataset_var_params
    params.require(:fmr_dataset).require(:dataset_var_attributes).
      permit(:sheetname, :fmr0, :fmr1, :fmr2, :fmr3, :fmr4, :metro_code, :metro_area, :area_name, :state)
  end

  def filename_params
    filename = params.require(:fmr_dataset).require(:dataset_var_attributes).permit(:filename)
  end
end

app/helpers/fmr_datasets_helper.rb
module FmrDatasetsHelper
end

app/views/fmr_datasets/_form.html.slim
= simple_form_for @fmr_dataset, { wrapper: :vertical_form } do |f|
  .row
    .col-sm-12
      = f.error_notification
  .form-inputs
    .row
      .col-sm-4
        = f.input :data_year, required: false
      .col-sm-8
        = f.input :requested_by, required: false
    .row
      .col-sm-12
        = f.input :description, required: false, as: :text
      .col-xs-12
        h3 : span.label.label-default Worksheet & Column Names
        = f.simple_fields_for :dataset_var do |fa|
          .row
            .col-sm-12
              = fa.input :sheetname, required: false, label: 'Worksheet name'
          .row
            .col-sm-2
              = fa.input :fmr0, required: false
            .col-sm-2
              = fa.input :fmr1, required: false
            .col-sm-2
              = fa.input :fmr2, required: false
            .col-sm-2
              = fa.input :fmr3, required: false
            .col-sm-2
              = fa.input :fmr4, required: false
          .row
            .col-sm-3
              = fa.input :metro_code, required: false
            .col-sm-3
              = fa.input :metro_area, required: false
            .col-sm-3
              = fa.input :area_name, required: false
            .col-sm-3
              = fa.input :state, required: false
          .row
            h3 : span.label.label-default Upload Excel File
            br
            .col-xs-12
              = fa.input :filename, required: false, as: :file, wrapper: :vertical_file_input
  .form-actions
    .row
      .col-xs-1.col-xs-offset-8
        = link_to 'Back', fmr_datasets_path, class: 'btn btn-link btn-lg'
      .col-xs-2
        = f.submit 'Upload to Database', class: 'btn btn-lg btn-primary'

app/views/fmr_datasets/edit.html.slim
h1 Editing fmr_dataset

== render 'form'

= link_to 'Show', @fmr_dataset
'|
= link_to 'Back', fmr_datasets_path

app/views/fmr_datasets/index.html.slim
h1 Listing fmr_datasets

table
  thead
    tr
      th Requested by
      th Data year
      th Method
      th Description
      th
      th
      th

  tbody
    - @fmr_datasets.each do |fmr_dataset|
      tr
        td = fmr_dataset.requested_by
        td = fmr_dataset.data_year
        td = fmr_dataset.method
        td = fmr_dataset.description
        td = link_to 'Show', fmr_dataset
        td = link_to 'Destroy', fmr_dataset, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Fmr dataset', new_fmr_dataset_path

app/views/fmr_datasets/new.html.slim
h1 Load Spreadsheet to Database

== render 'form'

app/views/fmr_datasets/show.html.slim
p#notice = notice

p
  strong Requested by:
  = @fmr_dataset.requested_by
p
  strong Data year:
  = @fmr_dataset.data_year
p
  strong Method:
  = @fmr_dataset.method
p
  strong Description:
  = @fmr_dataset.description

= link_to 'Back', fmr_datasets_path