config/routes.rb
Rails.application.routes.draw do

  resources :fmr_datasets, except: [:edit, :update]

  resources :fair_mkt_rents, only: [:index, :show]

  get '/ulw', to: 'ulw#show', as: :ulw
  get '/', to: 'ulw#search'
end

app/controllers/ulw_controller.rb
class UlwController < ApplicationController

  def show
    @fmr = FairMktRent.by_metro_code(metro_code_params)

    monthly_rent = @fmr['fmr' + params['bedrooms']]
    yearly_rent = monthly_rent.to_i * 12

    weekly_working_hours = 40
    yearly_working_hours = 52 * weekly_working_hours

    rent_percentage_of_income = 30.00 / 100.00

    ulw = ( yearly_rent / rent_percentage_of_income ) / yearly_working_hours
    ulw = ulw.round(2).to_s
    display_string = 'The Universal Living Wage for this type of housing in your area is: '
    display_string += view_context.number_to_currency(ulw) + ' per hour'

    render plain: display_string
  end

  def search
    @fmr_areas = FmrArea.map_by_state
    response.headers.delete 'X-Frame-Options'
  end

private
  def metro_code_params
    params.permit(:metro_code)
  end
end

app/helpers/ulw_helper.rb
module UlwHelper
  def state_opts(states)
    options_for_select(states.sort)
  end

  def area_opts(area)
    area.sort_by! { |a| a.area_name }
    options_from_collection_for_select(area, :metro_code, :area_name)
  end

  def state_attrs
    { prompt: 'Select state', class: 'form-control' }
  end

  def area_attrs
    { class: 'form-control' }
  end

  def bedroom_opts
    (0..4).map do |n|
      name = n == 0 ? 'Studio/Efficiency' : n.to_s
      [ name, n ]
    end
  end
end

app/views/ulw/search.html.slim
h3 Calculate For Your Area

= label_tag 'state'
= select_tag('state', state_opts(@fmr_areas.keys), state_attrs)
br
- @fmr_areas.each do |state, fmr_group|
  .collapse.state-form id=state
    ul.nav.nav-tabs
      li.active
        = link_to('By Metro Area', "##{state}metro", data: {toggle: 'tab'})
      li
        = link_to('By County or Town',  "##{state}rural", data: {toggle: 'tab'})
    br
    .tab-content
      - %w(metro rural).each do |area|
        .tab-pane id=(state + area) class=('active' if area == 'metro')
          = form_tag(ulw_path, {class: 'fmr-form', method: 'get', data: {remote: true}, id: "#{state}_#{area}"}) do
            = label_tag 'metro_code', 'Select Region'
            = select_tag 'metro_code', area_opts(fmr_group[area]), area_attrs
            br
            = label_tag 'bedrooms', 'Number of Bedrooms'
            = select_tag 'bedrooms', options_for_select(bedroom_opts), area_attrs
            br
            = submit_tag 'Calculate', class: 'btn btn-default btn-large'

br
p#response